name: Build Pacman Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Permite ejecutar manualmente

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame pyinstaller

    - name: Build Windows executable
      if: runner.os == 'Windows'
      run: |
        pyinstaller --onefile --windowed --name "PacmanVintage-Windows" pacman_game.py
        mkdir release
        copy dist\PacmanVintage-Windows.exe release\

    - name: Build macOS executable  
      if: runner.os == 'macOS'
      run: |
        pyinstaller --onefile --windowed --name "PacmanVintage-Mac" pacman_game.py
        mkdir release
        cp dist/PacmanVintage-Mac release/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pacman-${{ matrix.os }}
        path: release/
